Algoritmo "semnome"

Var
nome, email : caractere
idade : inteiro

inicio
escreval("boa tarde! digite seu nome: ")
leia(nome)
 limpatela()
escreval("digite a sua idade: ")
leia(idade)
limpatela()

escreval("digite o seu email")
leia(email)
limpatela()
escreval("****************")
escreval("usuario : ",nome)
 escreval("usuario : ",email)
 escreval("usuario : ",idade)
 escreval("muito obrigado, volte sempreS2")
Fimalgoritmo